### PR TITLE
Support Laravel 10

### PR DESCRIPTION
**Pull request by parkourben99**

### CODE REVIEW

**Comment by parkourben99** [comment]
Hi @ryangjchandler any chance you could review this?

**Comment by ryangjchandler** [comment]
Sorry @parkourben99, this one slipped under the radar, looking now!

**Review by ryangjchandler — CHANGES_REQUESTED** [review]
The run-tests action still needs to be updated to run on Laravel 10.x instead of 9.x

**Comment by parkourben99** [comment]
> The run-tests action still needs to be updated to run on Laravel 10.x instead of 9.x

Apologises. Have now updated them, but not sure how to trigger them to run.

**Pull request merged**
